### ISSUE TITLE
Crash when using gevent-profiler

### ISSUE THREAD

**Issue by c00w** [srlindsay/gevent-profiler#3]
The following crash is showing up:

[<greenlet.greenlet object at 0x7f31c19eab98>] call: threading: _note
[<greenlet.greenlet object at 0x7f31c19eab98>] return: threading: _note: 62
[<greenlet.greenlet object at 0x7f31c19eab98>] call: threading: __delete
[<greenlet.greenlet object at 0x7f31c19eab98>] return: threading: __delete: 613
[<greenlet.greenlet object at 0x7f31c19eab98>] return: threading: _exitfunc: 773
[<greenlet.greenlet object at 0x7f31c19eab98>] call: atexit: _run_exitfuncs
[<greenlet.greenlet object at 0x7f31c19eab98>] call: __init__: shutdown
[<greenlet.greenlet object at 0x7f31c19eab98>] return: **init**: shutdown: 1624
[<greenlet.greenlet object at 0x7f31c19eab98>] return: atexit: _run_exitfuncs: 13
Exception AttributeError: "'NoneType' object has no attribute 'greenlet'" in <function _remove at 0x7f31c195c8c0> ignored

**Comment by srlindsay** [comment]
You're seeing this crash at shutdown?  Can you post a minimal repro?

**Comment by c00w** [comment]
I'm seeing this crash at startup. gevent-profiler does not work for me.

**Comment by c00w** [comment]
@srlindsay Its working again. I'm not sure how it fixed itself but it did.
